# Generated by Django 4.2.11 on 2025-07-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='mbid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
