# Generated by Django 4.2.11 on 2025-07-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_artist_mbid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=100)),
                ('songs_per_artist', models.PositiveIntegerField(default=15)),
                ('n_setlists_per_artist', models.PositiveIntegerField(default=3)),
                ('use_unique_songs', models.BooleanField(default=True)),
                ('playlist_name', models.CharField(default='My Playlist', max_length=200)),
                ('one_big_playlist', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
