# Generated by Django 4.2.11 on 2025-07-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_playlistconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistconfiguration',
            name='selected_artists',
            field=models.ManyToManyField(blank=True, to='api.artist'),
        ),
    ]
