# Generated by Django 4.2.11 on 2025-07-02 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_playlistconfiguration_selected_artists'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={},
        ),
        migrations.RemoveField(
            model_name='song',
            name='order',
        ),
        migrations.RemoveField(
            model_name='song',
            name='setlist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='title',
        ),
        migrations.AddField(
            model_name='setlist',
            name='setlistfm_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='setlist',
            name='songs',
            field=models.ManyToManyField(to='api.song'),
        ),
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='TopSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_songs', to='api.artist')),
            ],
            options={
                'ordering': ['-count'],
                'unique_together': {('artist', 'title')},
            },
        ),
    ]
