# Generated by Django 4.2.11 on 2025-07-02 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_song_options_remove_song_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setlist',
            name='venue',
        ),
    ]
