# Generated by Django 4.2.11 on 2025-07-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_setlist_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistconfiguration',
            name='n_setlists_per_artist',
        ),
        migrations.AddField(
            model_name='topsong',
            name='n_setlists',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
