# Generated by Django 5.1.4 on 2025-07-04 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_playlistconfiguration_n_setlists_per_artist_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaylistConfiguration',
        ),
    ]
